package com.qqmu.jargus.datasource;

import com.qqmu.jargus.datasource.SqlDialectAdapter.Family;

import java.util.List;

/**
 * 方言级 DDL 片段渲染：启动/切换后的增量迁移（补列、补建表）要在任意活库上可执行，
 * 不能再用 H2/MySQL 专属语法（ADD IF NOT EXISTS、AUTO_INCREMENT、BOOLEAN、CLOB-TRIM 等）。
 * 类型与语法选择和 db/schema-*.sql 各方言脚本保持一致。
 */
public final class DialectDdl {

    private DialectDdl() {
    }

    /** 自增主键列定义（含列名 id） */
    public static String identityPk(Family f) {
        return switch (f) {
            case MYSQL, H2 -> "id BIGINT AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> "id BIGSERIAL PRIMARY KEY";
            case ORACLE -> "id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY";
            case SQLSERVER -> "id BIGINT IDENTITY(1,1) PRIMARY KEY";
            case DB2 -> "id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY";
            case CUSTOM -> "id BIGINT PRIMARY KEY";
        };
    }

    /** 非自增大整型主键列定义（gate_setting 固定 id=1） */
    public static String plainBigintPk(Family f) {
        return switch (f) {
            case ORACLE -> "id NUMBER(19) PRIMARY KEY";
            default -> "id BIGINT PRIMARY KEY";
        };
    }

    public static String varchar(Family f, int len) {
        return switch (f) {
            case ORACLE -> "VARCHAR2(" + len + ")";
            case SQLSERVER -> "NVARCHAR(" + len + ")";
            default -> "VARCHAR(" + len + ")";
        };
    }

    public static String text(Family f) {
        return switch (f) {
            case ORACLE, DB2 -> "CLOB";
            case SQLSERVER -> "NVARCHAR(MAX)";
            default -> "TEXT";
        };
    }

    public static String intType(Family f) {
        return f == Family.ORACLE ? "NUMBER(10)" : "INT";
    }

    /** 布尔列类型（Oracle 用 NUMBER(1)、SQL Server 用 BIT，与各方言脚本一致） */
    public static String boolType(Family f) {
        return switch (f) {
            case ORACLE -> "NUMBER(1)";
            case SQLSERVER -> "BIT";
            case DB2 -> "SMALLINT";
            default -> "BOOLEAN";
        };
    }

    /** 布尔字面量（Oracle/SQLServer/DB2 用 1/0） */
    public static String boolLiteral(Family f, boolean value) {
        return switch (f) {
            case ORACLE, SQLSERVER, DB2 -> value ? "1" : "0";
            default -> value ? "TRUE" : "FALSE";
        };
    }

    /** 带默认值的布尔列定义片段，如 "BOOLEAN DEFAULT TRUE" */
    public static String boolDefault(Family f, boolean value) {
        return boolType(f) + " DEFAULT " + boolLiteral(f, value);
    }

    /** 时间戳类型名（SQL Server 用 DATETIME2，其余 TIMESTAMP） */
    public static String tsType(Family f) {
        return f == Family.SQLSERVER ? "DATETIME2" : "TIMESTAMP";
    }

    /** 创建时间列（带 CURRENT_TIMESTAMP 默认值） */
    public static String timestampNow(String column, Family f) {
        return column + " " + tsType(f) + " DEFAULT CURRENT_TIMESTAMP";
    }

    public static String timestampCol(String column, Family f) {
        return column + " " + tsType(f);
    }

    /**
     * 加列语句（各方言均无 IF NOT EXISTS，存在性由 SchemaMetadata 守卫）：
     * MySQL/PG/H2/DB2 用 ADD COLUMN；Oracle 用 ADD (...)；SQL Server 用 ADD。
     */
    public static String addColumn(String table, String column, String typeSql, Family f) {
        return switch (f) {
            case ORACLE -> "ALTER TABLE " + table + " ADD (" + column + " " + typeSql + ")";
            case SQLSERVER -> "ALTER TABLE " + table + " ADD " + column + " " + typeSql;
            default -> "ALTER TABLE " + table + " ADD COLUMN " + column + " " + typeSql;
        };
    }

    /**
     * 文本列为空的谓词（用于回填 UPDATE）：
     * Oracle 空串即 NULL（CLOB 也不能 TRIM 比较）；SQL Server 2016 无 TRIM 函数，
     * 用 LTRIM(RTRIM())；其余库 TRIM 通用。
     */
    public static String isEmptyText(String column, Family f) {
        return switch (f) {
            case ORACLE -> column + " IS NULL";
            case SQLSERVER -> "(" + column + " IS NULL OR LTRIM(RTRIM(" + column + ")) = '')";
            default -> "(" + column + " IS NULL OR TRIM(" + column + ") = '')";
        };
    }

    /** 渲染完整建表语句（无 IF NOT EXISTS——存在性由 SchemaMetadata 守卫后再调用） */
    public static String createTable(String table, List<String> columnDefs, Family f) {
        StringBuilder sb = new StringBuilder("CREATE TABLE ").append(table).append(" (");
        for (int i = 0; i < columnDefs.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(columnDefs.get(i));
        }
        return sb.append(")").toString();
    }
}
