-- ============================================================
-- 百目 JArgus - Oracle Database Schema
-- 适用: Oracle 12c+ / 达梦 DM8 / 崖山 YashanDB（Oracle 兼容）
-- Version: 1.0.0
-- 说明: 自增列用 GENERATED BY DEFAULT ON NULL AS IDENTITY（允许显式 id 写入，
--       便于切换时整表复制）；布尔用 NUMBER(1)（1=真 0=假）；
--       Oracle 无 CREATE TABLE IF NOT EXISTS，本脚本仅在未检测到
--       schema_version 表时由应用执行；不含 database_config 种子行
-- ============================================================

-- ============================================================
-- 表 1: schema_version (表结构版本)
-- ============================================================
CREATE TABLE schema_version (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    version VARCHAR2(32) NOT NULL,
    description VARCHAR2(256),
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 2: database_config (数据库配置)
-- ============================================================
CREATE TABLE database_config (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(128) NOT NULL,
    db_type VARCHAR2(32) NOT NULL,
    driver_class VARCHAR2(256),
    jdbc_url VARCHAR2(512),
    username VARCHAR2(128),
    password VARCHAR2(512),
    max_pool_size NUMBER(10) DEFAULT 10,
    min_idle NUMBER(10) DEFAULT 5,
    connection_timeout NUMBER(10) DEFAULT 30000,
    dialect VARCHAR2(32),
    driver_jar_path VARCHAR2(512),
    connection_properties CLOB,
    is_custom NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 0,
    schema_version VARCHAR2(32),
    is_initialized NUMBER(1) DEFAULT 0,
    sort_order NUMBER(10) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 3: ai_provider_config (AI厂商配置)
-- ============================================================
CREATE TABLE ai_provider_config (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR2(64) NOT NULL,
    display_name VARCHAR2(128),
    protocol_type VARCHAR2(32) NOT NULL,
    base_url VARCHAR2(512),
    api_key VARCHAR2(512),
    secret_key VARCHAR2(512),
    default_model VARCHAR2(128),
    available_models CLOB,
    auth_type VARCHAR2(32) DEFAULT 'BEARER',
    auth_header_name VARCHAR2(128) DEFAULT 'Authorization',
    request_method VARCHAR2(16) DEFAULT 'POST',
    request_headers CLOB,
    request_body_template CLOB,
    response_content_path VARCHAR2(256),
    response_error_path VARCHAR2(256),
    timeout_seconds NUMBER(10) DEFAULT 60,
    max_tokens NUMBER(10),
    is_custom NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 0,
    is_enabled NUMBER(1) DEFAULT 1,
    sort_order NUMBER(10) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 4: llm_template (LLM配置模板)
-- ============================================================
CREATE TABLE llm_template (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    template_name VARCHAR2(128) NOT NULL,
    provider_name VARCHAR2(64),
    protocol_type VARCHAR2(32) NOT NULL,
    base_url VARCHAR2(512),
    auth_type VARCHAR2(32) DEFAULT 'BEARER',
    auth_header_name VARCHAR2(128) DEFAULT 'Authorization',
    request_body_template CLOB,
    response_content_path VARCHAR2(256),
    response_error_path VARCHAR2(256),
    default_model VARCHAR2(128),
    description VARCHAR2(512),
    is_builtin NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 5: scan_task (扫描任务)
-- ============================================================
CREATE TABLE scan_task (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    task_name VARCHAR2(256) NOT NULL,
    project_name VARCHAR2(256),
    source_type VARCHAR2(32) NOT NULL,
    status VARCHAR2(32) DEFAULT 'PENDING',
    total_files NUMBER(10) DEFAULT 0,
    total_lines NUMBER(10) DEFAULT 0,
    blocker_count NUMBER(10) DEFAULT 0,
    critical_count NUMBER(10) DEFAULT 0,
    major_count NUMBER(10) DEFAULT 0,
    minor_count NUMBER(10) DEFAULT 0,
    info_count NUMBER(10) DEFAULT 0,
    total_issues NUMBER(10) DEFAULT 0,
    jdk_version VARCHAR2(32),
    spring_boot_version VARCHAR2(32),
    skip_unit_test NUMBER(1) DEFAULT 0,
    include_test_code NUMBER(1) DEFAULT 0,
    enable_ai_review NUMBER(1) DEFAULT 1,
    ai_issue_count NUMBER(10) DEFAULT 0,
    notify_enabled NUMBER(1) DEFAULT 0,
    notify_recipient_ids VARCHAR2(512),
    mail_status VARCHAR2(16),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    duration_seconds NUMBER(19) DEFAULT 0,
    error_message CLOB,
    snapshot_path VARCHAR2(512),
    report_path VARCHAR2(512),
    created_by VARCHAR2(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 6: scan_issue (扫描问题详情)
-- ============================================================
CREATE TABLE scan_issue (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    task_id NUMBER(19) NOT NULL,
    file_path VARCHAR2(512) NOT NULL,
    file_name VARCHAR2(256),
    line_start NUMBER(10),
    line_end NUMBER(10),
    column_start NUMBER(10),
    column_end NUMBER(10),
    line_points CLOB,
    occurrence_count NUMBER(10) DEFAULT 1,
    issue_level VARCHAR2(16) NOT NULL,
    checker_type VARCHAR2(64) NOT NULL,
    checker_name VARCHAR2(128),
    rule_code VARCHAR2(64),
    title VARCHAR2(256) NOT NULL,
    description CLOB,
    code_snippet CLOB,
    suggestion CLOB,
    severity NUMBER(10) DEFAULT 1,
    is_ai_generated NUMBER(1) DEFAULT 0,
    is_ignored NUMBER(1) DEFAULT 0,
    ignore_type VARCHAR2(32),
    ignore_reason VARCHAR2(512),
    ai_explanation CLOB,
    ai_suggestion CLOB,
    ai_suggestion_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scan_issue_task_id ON scan_issue (task_id);
CREATE INDEX idx_scan_issue_file_path ON scan_issue (file_path);
CREATE INDEX idx_scan_issue_issue_level ON scan_issue (issue_level);

-- ============================================================
-- 表 7: ignore_rule (强制忽略规则)
-- ============================================================
CREATE TABLE ignore_rule (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    rule_type VARCHAR2(32) NOT NULL,
    rule_code VARCHAR2(64),
    file_pattern VARCHAR2(512),
    file_path VARCHAR2(512),
    line_number NUMBER(10),
    reason VARCHAR2(512),
    is_enabled NUMBER(1) DEFAULT 1,
    created_by VARCHAR2(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 8: review_rule (评审规则配置)
-- ============================================================
CREATE TABLE review_rule (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR2(64) NOT NULL UNIQUE,
    rule_name VARCHAR2(128) NOT NULL,
    rule_category VARCHAR2(64),
    description CLOB,
    default_level VARCHAR2(16) DEFAULT 'MAJOR',
    is_enabled NUMBER(1) DEFAULT 1,
    is_builtin NUMBER(1) DEFAULT 1,
    params CLOB,
    sort_order NUMBER(10) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 9: checker_config (检查器配置)
-- ============================================================
CREATE TABLE checker_config (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    checker_code VARCHAR2(64) NOT NULL UNIQUE,
    checker_name VARCHAR2(128) NOT NULL,
    checker_category VARCHAR2(64),
    description CLOB,
    is_enabled NUMBER(1) DEFAULT 1,
    is_local NUMBER(1) DEFAULT 1,
    params CLOB,
    sort_order NUMBER(10) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 10: ci_trigger_config (CI触发配置)
-- ============================================================
CREATE TABLE ci_trigger_config (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    config_name VARCHAR2(128) NOT NULL,
    platform VARCHAR2(32),
    platform_url VARCHAR2(256),
    repo_scope VARCHAR2(256),
    webhook_url VARCHAR2(512),
    secret_token VARCHAR2(256),
    repo_username VARCHAR2(128),
    repo_token VARCHAR2(512),
    branch_filter VARCHAR2(256),
    skip_unit_test NUMBER(1) DEFAULT 0,
    include_test_code NUMBER(1) DEFAULT 0,
    enable_ai_review NUMBER(1) DEFAULT 1,
    auto_comment NUMBER(1) DEFAULT 0,
    notify_enabled NUMBER(1) DEFAULT 0,
    notify_recipient_ids VARCHAR2(512),
    is_enabled NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 11: ci_scan_record (CI扫描记录)
-- ============================================================
CREATE TABLE ci_scan_record (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    trigger_config_id NUMBER(19),
    task_id NUMBER(19),
    platform VARCHAR2(32),
    project_url VARCHAR2(512),
    commit_id VARCHAR2(128),
    branch VARCHAR2(128),
    mr_pr_id VARCHAR2(64),
    mr_pr_title VARCHAR2(256),
    author VARCHAR2(128),
    status VARCHAR2(32) DEFAULT 'PENDING',
    result_url VARCHAR2(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 12: ci_token (CI令牌)
-- ============================================================
CREATE TABLE ci_token (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    token_name VARCHAR2(128) NOT NULL,
    token_value VARCHAR2(256) NOT NULL UNIQUE,
    description VARCHAR2(512),
    is_enabled NUMBER(1) DEFAULT 1,
    expires_at TIMESTAMP,
    last_used_at TIMESTAMP,
    created_by VARCHAR2(128),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 13: sys_user (系统用户)
-- ============================================================
CREATE TABLE sys_user (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(64) NOT NULL UNIQUE,
    password_hash VARCHAR2(256) NOT NULL,
    nickname VARCHAR2(128),
    role VARCHAR2(32) DEFAULT 'VIEWER' NOT NULL,
    source VARCHAR2(32) DEFAULT 'LOCAL' NOT NULL,
    is_enabled NUMBER(1) DEFAULT 1,
    is_password_default NUMBER(1) DEFAULT 1,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 默认用户由应用首次启动时创建（BCrypt 加密）：
--   admin / 123456  （管理员，ADMIN）
--   view  / 123456  （只读用户，VIEWER）
-- 见 AuthService.initDefaultUsers()

-- ============================================================
-- 表 14: remote_auth_config (远端登录配置)
-- ============================================================
CREATE TABLE remote_auth_config (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    config_name VARCHAR2(128) NOT NULL,
    auth_type VARCHAR2(32) DEFAULT 'OAUTH2' NOT NULL,
    login_url VARCHAR2(512),
    user_info_url VARCHAR2(512),
    token_url VARCHAR2(512),
    client_id VARCHAR2(256),
    client_secret VARCHAR2(512),
    username_field VARCHAR2(64),
    nickname_field VARCHAR2(128),
    role_field VARCHAR2(64),
    role_mapping CLOB,
    is_enabled NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 15: sys_oper_log (操作日志)
-- ============================================================
CREATE TABLE sys_oper_log (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(64),
    operation VARCHAR2(128),
    method VARCHAR2(16),
    params CLOB,
    ip VARCHAR2(64),
    status VARCHAR2(16),
    error_msg VARCHAR2(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 16: gate_setting (质量门禁自定义配置，单行 id=1；无行=用 application.yml 默认值)
-- ============================================================
CREATE TABLE gate_setting (
    id NUMBER(19) PRIMARY KEY,
    blocker_weight NUMBER(10) NOT NULL,
    critical_weight NUMBER(10) NOT NULL,
    major_weight NUMBER(10) NOT NULL,
    minor_weight NUMBER(10) NOT NULL,
    info_weight NUMBER(10) NOT NULL,
    pass_score NUMBER(10) NOT NULL,
    blocker_limit NUMBER(10) NOT NULL,
    excellent_score NUMBER(10) NOT NULL,
    good_score NUMBER(10) NOT NULL,
    fair_score NUMBER(10) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 17: mail_sender (发件配置；同一时间仅允许一条 is_enabled=1，由服务层保证)
-- ============================================================
CREATE TABLE mail_sender (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(128) NOT NULL,
    host VARCHAR2(256) NOT NULL,
    port NUMBER(10) DEFAULT 465 NOT NULL,
    password VARCHAR2(512),
    from_address VARCHAR2(256) NOT NULL,
    from_alias VARCHAR2(128),
    use_starttls NUMBER(1) DEFAULT 0,
    use_ssl NUMBER(1) DEFAULT 1,
    is_enabled NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 表 18: mail_recipient (扫描通知邮件收件人)
-- ============================================================
CREATE TABLE mail_recipient (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(128) NOT NULL,
    email VARCHAR2(256) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 初始化数据（Oracle 不支持多行 VALUES，逐条 INSERT）
-- ============================================================

-- 插入 schema 版本
INSERT INTO schema_version (version, description) VALUES ('1.0.0', '初始版本');

-- 注意：database_config 种子行由切换流程写入，脚本不预置（避免出现双 active）

-- 插入内置 LLM 模板
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('OpenAI 兼容', 'openai', 'OPENAI_COMPATIBLE', 'https://api.openai.com/v1', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7,"max_tokens":4096}', 'choices[0].message.content', 'error.message', 'gpt-4', 'OpenAI 兼容协议通用模板', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('阿里百炼', 'qwen', 'OPENAI_COMPATIBLE', 'https://dashscope.aliyuncs.com/compatible-mode/v1', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'message', 'qwen-plus', '阿里百炼通义千问', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('火山方舟', 'doubao', 'OPENAI_COMPATIBLE', 'https://ark.cn-beijing.volces.com/api/v3', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'doubao-pro', '火山引擎方舟', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('DeepSeek', 'deepseek', 'OPENAI_COMPATIBLE', 'https://api.deepseek.com/v1', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'deepseek-chat', 'DeepSeek', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('Kimi', 'kimi', 'OPENAI_COMPATIBLE', 'https://api.moonshot.cn/v1', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'moonshot-v1-8k', 'Kimi 月之暗面', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('智谱 GLM', 'zhipu', 'OPENAI_COMPATIBLE', 'https://open.bigmodel.cn/api/paas/v4', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'glm-4', '智谱清言', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('百度千帆', 'qianfan', 'OPENAI_COMPATIBLE', 'https://qianfan.baidubce.com/v2', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'ernie-4.0-turbo-8k', '百度千帆（OpenAI 兼容端点）', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('Gemini', 'gemini', 'OPENAI_COMPATIBLE', 'https://generativelanguage.googleapis.com/v1beta/openai', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'gemini-2.0-flash', 'Google Gemini（OpenAI 兼容端点）', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('Claude', 'claude', 'ANTHROPIC', 'https://api.anthropic.com/v1', 'API_KEY_HEADER', 'x-api-key', NULL, 'content[0].text', 'error.message', 'claude-3-5-sonnet-latest', 'Anthropic Claude（x-api-key 鉴权）', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('Ollama', 'ollama', 'OPENAI_COMPATIBLE', 'http://localhost:11434/v1', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'llama3', 'Ollama 本地部署（OpenAI 兼容）', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('vLLM', 'vllm', 'OPENAI_COMPATIBLE', 'http://localhost:8000/v1', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'default', 'vLLM 私有部署（OpenAI 兼容）', 1);
INSERT INTO llm_template (template_name, provider_name, protocol_type, base_url, auth_type, auth_header_name, request_body_template, response_content_path, response_error_path, default_model, description, is_builtin)
VALUES ('LocalAI', 'localai', 'OPENAI_COMPATIBLE', 'http://localhost:8080/v1', 'BEARER', 'Authorization', '{"model":"${model}","messages":[{"role":"system","content":"${system_prompt}"},{"role":"user","content":"${user_prompt}"}],"temperature":0.7}', 'choices[0].message.content', 'error.message', 'gpt4all-j', 'LocalAI 本地部署（OpenAI 兼容）', 1);

-- 插入默认检查器配置
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('compilation', '编译诊断', '基础', '使用 javax.tools 进行编译，获取编译错误和警告', 1, 1, 1);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('nullpointer', '空指针检测', '缺陷', '基于AST分析潜在的空指针风险', 1, 1, 2);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('unused_method', '未使用方法检测', '冗余', '基于调用图分析未被调用的方法', 1, 1, 3);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('deprecated_method', '废弃方法检测', '兼容性', '检测使用了 @Deprecated 注解的方法', 1, 1, 4);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('complexity', '圈复杂度检测', '质量', '检测圈复杂度超标的方法', 1, 1, 5);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('naming', '命名规范检查', '风格', '检查类、方法、变量命名是否符合规范', 1, 1, 6);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('code_style', '代码风格检查', '风格', '检查代码风格问题，如魔法数字、过长方法等', 1, 1, 7);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('duplicate_code', '重复代码检测', '冗余', '检测重复的代码块', 1, 1, 8);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('exception_handling', '异常处理检查', '缺陷', '检查异常处理不当的问题', 1, 1, 9);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('resource_leak', '资源泄露检测', '缺陷', '检测未正确关闭的资源', 1, 1, 10);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('security', '安全漏洞检测', '安全', '检测常见的安全漏洞', 1, 1, 11);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('concurrency', '并发问题检测', '并发', '检测多线程并发问题', 1, 1, 12);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('performance', '性能问题检测', '性能', '检测常见性能问题', 1, 1, 13);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('spring_best_practice', 'Spring最佳实践', '框架', '检查Spring使用的最佳实践', 1, 1, 14);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('ai_semantic', 'AI语义评审', 'AI', '使用AI进行语义级代码评审', 1, 0, 15);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('ai_security', 'AI安全评审', 'AI', '使用AI进行安全漏洞深度分析', 1, 0, 16);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('ai_design', 'AI设计评审', 'AI', '使用AI进行代码设计评审', 1, 0, 17);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('architecture', '架构约束检查', '架构', '检查分层架构约束：控制器不得跨层访问DAO、下层不得反向依赖上层、实体不得泄漏到接口层', 1, 1, 18);
INSERT INTO checker_config (checker_code, checker_name, checker_category, description, is_enabled, is_local, sort_order) VALUES ('dependency_vuln', '依赖漏洞扫描', '依赖', '解析pom.xml/build.gradle依赖，与内置漏洞库匹配已知CVE（可选OSV在线增强）', 1, 1, 19);

-- 插入默认评审规则
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('MAX_COMPLEXITY', '最大圈复杂度', '质量', '方法的圈复杂度超过阈值时告警', 'MAJOR', 1, 1, 1);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('MAX_METHOD_LENGTH', '最大方法长度', '风格', '方法行数超过阈值时告警', 'MINOR', 1, 1, 2);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('MAX_FILE_LENGTH', '最大文件长度', '风格', '文件行数超过阈值时告警', 'MINOR', 1, 1, 3);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('NAMING_CLASS', '类命名规范', '风格', '类名应使用大驼峰命名法', 'MAJOR', 1, 1, 4);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('NAMING_METHOD', '方法命名规范', '风格', '方法名应使用小驼峰命名法', 'MINOR', 1, 1, 5);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('MAGIC_NUMBER', '魔法数字', '风格', '避免使用魔法数字，应定义常量', 'MINOR', 1, 1, 6);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('EMPTY_CATCH', '空catch块', '缺陷', 'catch块不能为空', 'MAJOR', 1, 1, 7);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('SYSTEM_OUT', 'System.out输出', '风格', '生产代码应使用日志框架而非System.out', 'MAJOR', 1, 1, 8);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('UNUSED_IMPORT', '未使用的import', '冗余', '应删除未使用的import语句', 'MINOR', 1, 1, 9);
INSERT INTO review_rule (rule_code, rule_name, rule_category, description, default_level, is_enabled, is_builtin, sort_order) VALUES ('NULL_CHECK', '空指针风险', '缺陷', '可能存在空指针异常风险', 'CRITICAL', 1, 1, 10);
